# Generated by Django 5.2.2 on 2025-06-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account for this transaction (uses default if not specified)', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account'),
        ),
    ]
